# Generated by Django 3.0.3 on 2020-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='name',
            field=models.TextField(default='TemplateName'),
            preserve_default=False,
        ),
    ]
