# Generated by Django 3.0.3 on 2020-02-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_overlay_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Overlay',
            new_name='Template',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template',
            new_name='overlays',
        ),
    ]
