# Generated by Django 3.0.3 on 2020-04-01 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stream_key', models.TextField()),
                ('process_ids', models.TextField()),
            ],
        ),
    ]
